<testsuite errors="0" failures="5" name="Django Project Tests" skips="0" tests="6" time="0.037"><testcase classname="book.tests.BookModelTestCase" name="test_buscar_libro_por_autor" time="0.001002"><failure message="1 != 0" type="builtins.AssertionError">Traceback (most recent call last):
  File "C:\Users\Luis ZR\Desktop\Pruebas de integracion con jenkins\Django\Libreria\book\tests.py", line 31, in test_buscar_libro_por_autor
    self.assertEqual(1,0)
AssertionError: 1 != 0
</failure></testcase><testcase classname="book.tests.BookModelTestCase" name="test_buscar_un_libro" time="0.000000"><failure message="1 != 0" type="builtins.AssertionError">Traceback (most recent call last):
  File "C:\Users\Luis ZR\Desktop\Pruebas de integracion con jenkins\Django\Libreria\book\tests.py", line 27, in test_buscar_un_libro
    self.assertEqual(1,0)
AssertionError: 1 != 0
</failure></testcase><testcase classname="book.tests.BookModelTestCase" name="test_crear_libro" time="0.000000" /><testcase classname="book.tests.BookModelTestCase" name="test_editar_libro" time="0.000000"><failure message="1 != 0" type="builtins.AssertionError">Traceback (most recent call last):
  File "C:\Users\Luis ZR\Desktop\Pruebas de integracion con jenkins\Django\Libreria\book\tests.py", line 35, in test_editar_libro
    self.assertEqual(1,0)
AssertionError: 1 != 0
</failure></testcase><testcase classname="book.tests.BookModelTestCase" name="test_obtener_ruta_aboluta" time="0.000000"><failure message="1 != 0" type="builtins.AssertionError">Traceback (most recent call last):
  File "C:\Users\Luis ZR\Desktop\Pruebas de integracion con jenkins\Django\Libreria\book\tests.py", line 39, in test_obtener_ruta_aboluta
    self.assertEqual(1,0)
AssertionError: 1 != 0
</failure></testcase><testcase classname="book.tests.BookViewTests" name="test_home_page" time="0.029316"><failure message="False is not true : Template 'book/book_list.html' was not a template used to render the response. Actual template(s) used: book/book_form.html, book/base.html, django/forms/widgets/text.html, django/forms/widgets/input.html, django/forms/widgets/attrs.html, django/forms/widgets/text.html, django/forms/widgets/input.html, django/forms/widgets/attrs.html, django/forms/widgets/text.html, django/forms/widgets/input.html, django/forms/widgets/attrs.html" type="builtins.AssertionError">Traceback (most recent call last):
  File "C:\Users\Luis ZR\Desktop\Pruebas de integracion con jenkins\Django\Libreria\book\tests.py", line 49, in test_home_page
    self.assertTemplateUsed(response, 'book/book_list.html')
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\django\test\testcases.py", line 644, in assertTemplateUsed
    % (template_name, ', '.join(template_names))
AssertionError: False is not true : Template 'book/book_list.html' was not a template used to render the response. Actual template(s) used: book/book_form.html, book/base.html, django/forms/widgets/text.html, django/forms/widgets/input.html, django/forms/widgets/attrs.html, django/forms/widgets/text.html, django/forms/widgets/input.html, django/forms/widgets/attrs.html, django/forms/widgets/text.html, django/forms/widgets/input.html, django/forms/widgets/attrs.html
</failure></testcase></testsuite>